// Firestore rules tests against ../../firestore.rules on the local emulator (needs Java).
// Run from tests/: `npm run test:rules`. The family code in the rules file is the placeholder
// FAMILY_CODE, so the tests join with that. Each t() line is one allow/deny case.
import { initializeTestEnvironment, assertSucceeds as ok, assertFails as no } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { Timestamp, doc, setDoc, getDoc, getDocs, addDoc, deleteDoc, collection, serverTimestamp, writeBatch, query, where } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'demo-bingo', firestore: { rules: readFileSync(new URL('../../firestore.rules', import.meta.url),'utf8'), host:'127.0.0.1', port:8080 } });
const db = u => u ? env.authenticatedContext(u).firestore() : env.unauthenticatedContext().firestore();
const A = db('adminU'), K = db('kidU'), X = db('strangerU'), anon = db(null);
let n=0, bad=0; const t = async (name, p) => { try { await p; n++; } catch(e) { bad++; console.log('FAIL', name, e.message.split('\n')[0]); } };
const add = (d, author, about='אבא', {text='עוד 5 דקות', id, ...meta}={}) => {
  const r = id ? doc(d,'items',id) : doc(collection(d,'items')); const b = writeBatch(d);
  b.set(r, {about, author, weight:1, at: serverTimestamp(), ...meta}); b.set(doc(d,'texts',r.id), {text});
  return b.commit().then(() => r);
};
const del = (d, id) => { const b = writeBatch(d); b.delete(doc(d,'items',id)); b.delete(doc(d,'texts',id)); return b.commit(); };

await t('anon read items', no(getDocs(collection(anon,'items'))));
await t('stranger read items', no(getDocs(collection(X,'items'))));
await t('wrong code', no(setDoc(doc(X,'members','strangerU'), {code:'nope'})));
await t('join for other uid', no(setDoc(doc(X,'members','kidU'), {code:'FAMILY_CODE'})));
await t('stranger claim', no(setDoc(doc(X,'players','עדי'), {uid:'strangerU'})));
await t('admin join', ok(setDoc(doc(A,'members','adminU'), {code:'FAMILY_CODE'})));
await t('kid join', ok(setDoc(doc(K,'members','kidU'), {code:'FAMILY_CODE'})));
await t('get own member', ok(getDoc(doc(K,'members','kidU'))));
await t('get other member', no(getDoc(doc(K,'members','adminU'))));
await t('admin claim', ok(setDoc(doc(A,'players','מתן'), {uid:'adminU'})));
await t('member takes over a taken name', ok(setDoc(doc(K,'players','מתן'), {uid:'kidU'})));
await t('takeover only to own uid', no(setDoc(doc(K,'players','מתן'), {uid:'adminU'})));
await t('stranger cannot take over', no(setDoc(doc(X,'players','מתן'), {uid:'strangerU'})));
await t('takeover extra field', no(setDoc(doc(K,'players','מתן'), {uid:'kidU', x:1})));
await t('owner takes the name back', ok(setDoc(doc(A,'players','מתן'), {uid:'adminU'})));
await t('kid claim for other uid', no(setDoc(doc(K,'players','עדי'), {uid:'adminU'})));
await t('kid claim bad name', no(setDoc(doc(K,'players','hacker'), {uid:'kidU'})));
await t('kid claim', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'})));
await t('member read items', ok(getDocs(collection(K,'items'))));
await t('item ok', ok(add(K, 'עדי')));
await t('item impersonate', no(add(K, 'אמא')));
await t('item about self', no(add(K, 'עדי','עדי')));
await t('item too long', no(add(K, 'עדי','אבא',{text:'x'.repeat(141)})));
await t('item extra field', no(add(K, 'עדי','אבא',{evil:1})));
await t('item weight', no(add(K, 'עדי','אבא',{weight:99})));
await t('item custom id xss', no(add(K, 'עדי', 'אבא', {id:'"><img src=x onerror=alert(1)>'})));
const kidItem = await add(K, 'עדי');
const admItem = await add(A, 'מתן','עדי');
await t('kid delete admin item', no(del(K, admItem.id)));
await t('item without text', no(addDoc(collection(K,'items'), {about:'אבא', author:'עדי', weight:1, at: serverTimestamp()})));
await t('text without item', no(setDoc(doc(K,'texts','abcdefghijklmnopqrst'), {text:'x'})));
await t('item with text field', no(add(K, 'עדי', 'אבא', {extraText:'x'})));
await t('entry: author reads own text', ok(getDoc(doc(K,'texts',kidItem.id))));
await t('entry: admin cannot read kid text', no(getDoc(doc(A,'texts',kidItem.id))));
await t('entry: kid cannot read admin text', no(getDoc(doc(K,'texts',admItem.id))));
await t('entry: kid cannot list texts', no(getDocs(collection(K,'texts'))));
await t('stranger cannot read text', no(getDoc(doc(X,'texts',kidItem.id))));
await t('entry: author edits own text', ok(setDoc(doc(K,'texts',kidItem.id), {text:'ניסוח חדש'})));
await t('entry: edit too long', no(setDoc(doc(K,'texts',kidItem.id), {text:'x'.repeat(141)})));
await t('entry: edit extra field', no(setDoc(doc(K,'texts',kidItem.id), {text:'a', x:1})));
await t('entry: admin cannot edit kid text', no(setDoc(doc(A,'texts',kidItem.id), {text:'hack'})));
await t('kid update item', no(setDoc(doc(K,'items',kidItem.id), {about:'אמא', author:'עדי', weight:1, at: serverTimestamp()})));
await t('kid write game', no(setDoc(doc(K,'game','state'), {status:'entry', cards:{}})));
await t('kid write other marks', no(setDoc(doc(K,'marks','מתן'), {marked:[],bingo:true,blackout:true})));
await t('kid write own marks in entry', no(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:false,blackout:false})));
await t('marks junk', no(setDoc(doc(K,'marks','עדי'), {marked:'x',bingo:false,blackout:false})));
const b = writeBatch(A);
b.set(doc(A,'game','state'), {status:'play', cards:{'עדי':['a']}, at: serverTimestamp()});
['אבא','אמא','מתן','עדי','עדי','הדר'].forEach(p => b.set(doc(A,'marks',p), {marked:[],bingo:false,blackout:false}));
await t('admin generate batch', ok(b.commit()));
await t('play: kid write own marks', ok(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:true,blackout:false,bingoAt:serverTimestamp(),blackoutAt:null})));
await t('play: keep same bingoAt', ok(getDoc(doc(K,'marks','עדי')).then(s=>setDoc(doc(K,'marks','עדי'), {...s.data(), marked:['a','b']}))));
await t('play: forged bingoAt', no(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:true,blackout:false,bingoAt:Timestamp.fromDate(new Date(2000,1,1)),blackoutAt:null})));
await t('play: marks too many', no(setDoc(doc(K,'marks','עדי'), {marked:Array(26).fill('x'),bingo:false,blackout:false})));
await t('play: admin reads kid text (about אבא)', ok(getDoc(doc(A,'texts',kidItem.id))));
await t('play: kid cannot read text about himself', no(getDoc(doc(K,'texts',admItem.id))));
await t('item during play', no(add(K, 'עדי')));
await t('own delete during play', no(del(K, kidItem.id)));
await t('admin reset', ok(setDoc(doc(A,'game','state'), {status:'entry', cards:{}})));
await t('own delete in entry', ok(del(K, kidItem.id)));
await t('admin delete kid item', ok(del(A, admItem.id)));
await t('kid release admin', no(deleteDoc(doc(K,'players','מתן'))));
await t('admin release kid', ok(deleteDoc(doc(A,'players','עדי'))));
await t('kid reclaim', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'})));
await t('kid release self', ok(deleteDoc(doc(K,'players','עדי'))));
await t('kid set own look', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'}).then(()=>setDoc(doc(K,'looks','עדי'), {e:'🚀'}))));
await t('kid look not in list', no(setDoc(doc(K,'looks','עדי'), {e:'💩'})));
await t('kid look extra field', no(setDoc(doc(K,'looks','עדי'), {e:'🚀', x:1})));
await t('kid set other look', no(setDoc(doc(K,'looks','אמא'), {e:'🚀'})));
await t('stranger read looks', no(getDocs(collection(X,'looks'))));
const U = db('uriU');
await t('uri join+claim', ok(setDoc(doc(U,'members','uriU'), {code:'FAMILY_CODE'}).then(()=>setDoc(doc(U,'players','אורי'), {uid:'uriU'}))));
await t('uri admin: write game', ok(setDoc(doc(U,'game','state'), {status:'entry', cards:{}})));
await t('uri admin: set other look', ok(setDoc(doc(U,'looks','אמא'), {e:'👻'})));
await t('uri admin: release kid', ok(deleteDoc(doc(U,'players','עדי'))));
await t('kid (released) write own marks', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
// ---- rating phase, sizes, history ----
const M = db('momU');
await setDoc(doc(K,'players','עדי'), {uid:'kidU'});
await setDoc(doc(M,'members','momU'), {code:'FAMILY_CODE'}); await setDoc(doc(M,'players','אמא'), {uid:'momU'});
const itA = await add(A,'מתן','אמא'), itK = await add(K,'עדי','אבא'), itM = await add(M,'אמא','עדי');
const rt = (d, item, player, stars, id) => setDoc(doc(d,'ratings', id ?? `${item}_${player}`), {item, player, stars});
await t('entry: kid cannot rate', no(rt(K, itA.id, 'עדי', 3)));
await t('kid cannot start rating', no(setDoc(doc(K,'game','state'), {status:'rate', cards:{}, raters:['עדי'], raterUids:['kidU']})));
await t('admin: bad rater name', no(setDoc(doc(A,'game','state'), {status:'rate', cards:{}, raters:['hacker']})));
await t('admin starts rating', ok(setDoc(doc(A,'game','state'), {status:'rate', cards:{}, raters:['עדי','מתן'], raterUids:['kidU','adminU'], at: serverTimestamp()})));
await t('admin syncs raterUids (merge)', ok(setDoc(doc(A,'game','state'), {raterUids:['kidU','adminU']}, {merge:true})));
await t('kid cannot sync raterUids', no(setDoc(doc(K,'game','state'), {raterUids:['kidU']}, {merge:true})));
await t('rate: rater reads text', ok(getDoc(doc(K,'texts',itA.id))));
await t('rate: non-rater cannot read text', no(getDoc(doc(M,'texts',itK.id))));
await t('rate: rater cannot read text about self', no(getDoc(doc(K,'texts',itM.id))));
await t('rate: author still reads own', ok(getDoc(doc(M,'texts',itM.id))));
await t('rate: kid rates', ok(rt(K, itA.id, 'עדי', 3)));
await t('rate: kid changes rating', ok(rt(K, itA.id, 'עדי', 0)));
await t('rate: about self', no(rt(K, itM.id, 'עדי', 3)));
await t('rate: own prediction', no(rt(K, itK.id, 'עדי', 3)));
await t('rate: 4 stars', no(rt(K, itA.id, 'עדי', 4)));
await t('rate: as someone else', no(rt(K, itA.id, 'מתן', 3)));
await t('rate: id mismatch', no(rt(K, itA.id, 'עדי', 3, 'whatever')));
await t('rate: non-rater', no(rt(M, itK.id, 'אמא', 3)));
await t('rate: extra field', no(setDoc(doc(K,'ratings',`${itA.id}_עדי`), {item:itA.id, player:'עדי', stars:1, x:1})));
await t('rate: add item locked', no(add(K, 'עדי')));
await t('rate: delete item locked', no(del(K, itK.id)));
await t('rate: author edits own text', ok(setDoc(doc(M,'texts',itM.id), {text:'ניסוח משופר'})));
await t('rate: rater cannot edit others text', no(setDoc(doc(K,'texts',itA.id), {text:'hack'})));
// suggestions: raters propose wording, only author (toUid) and suggester (fromUid) see them
const sg = (d, item, from, fromUid, toUid, extra={}) => addDoc(collection(d,'suggestions'), {item, from, fromUid, toUid, text:'הצעה', at: serverTimestamp(), ...extra});
await t('suggest: rater on others prediction', ok(sg(K, itA.id, 'עדי', 'kidU', 'adminU')));
await t('suggest: about self', no(sg(K, itM.id, 'עדי', 'kidU', 'momU')));
await t('suggest: on own prediction', no(sg(K, itK.id, 'עדי', 'kidU', 'kidU')));
await t('suggest: wrong author device', no(sg(K, itA.id, 'עדי', 'kidU', 'momU')));
await t('suggest: forged fromUid', no(sg(K, itA.id, 'עדי', 'adminU', 'adminU')));
await t('suggest: non-rater', no(sg(M, itK.id, 'אמא', 'momU', 'kidU')));
await t('suggest: too long', no(sg(K, itA.id, 'עדי', 'kidU', 'adminU', {text:'x'.repeat(141)})));
await t('suggest: extra field', no(sg(K, itA.id, 'עדי', 'kidU', 'adminU', {x:1})));
await t('suggest: author lists own', ok(getDocs(query(collection(A,'suggestions'), where('toUid','==','adminU')))));
await t('suggest: suggester lists own', ok(getDocs(query(collection(K,'suggestions'), where('fromUid','==','kidU')))));
await t('suggest: others cannot list', no(getDocs(query(collection(M,'suggestions'), where('toUid','==','adminU')))));
await t('suggest: nobody lists all', no(getDocs(collection(A,'suggestions'))));
const mySug = (await getDocs(query(collection(A,'suggestions'), where('toUid','==','adminU')))).docs[0];
await t('suggest: author accepts (edit text + delete)', ok((() => { const b = writeBatch(A); b.set(doc(A,'texts',itA.id), {text:'הצעה'}); b.delete(doc(A,'suggestions',mySug.id)); return b.commit(); })()));
await t('rate: marks locked', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
await t('members read ratings', ok(getDocs(collection(M,'ratings'))));
await t('admin: size 6', no(setDoc(doc(A,'game','state'), {status:'play', cards:{}, size:6})));
await t('admin: bad status', no(setDoc(doc(A,'game','state'), {status:'weird', cards:{}})));
await t('admin: play 4x4', ok(setDoc(doc(A,'game','state'), {status:'play', cards:{'עדי':[itA.id]}, size:4, at: serverTimestamp()})));
await t('play: suggestions locked', no(sg(K, itA.id, 'עדי', 'kidU', 'adminU')));
await t('play: text edit locked', no(setDoc(doc(M,'texts',itM.id), {text:'late'})));
await t('play: rating locked', no(rt(K, itA.id, 'עדי', 2)));
await t('history: kid cannot write', no(addDoc(collection(K,'history'), {at: serverTimestamp(), size:4, results:[]})));
await t('history: extra field', no(addDoc(collection(A,'history'), {at: serverTimestamp(), size:4, results:[], x:1})));
await t('history: admin saves + ends', ok((() => { const b = writeBatch(A); b.set(doc(collection(A,'history')), {at: serverTimestamp(), size:4, results:[{p:'עדי', place:1, n:3, bingo:true, blackout:false}]}); b.set(doc(A,'game','state'), {status:'ended', cards:{'עדי':[itA.id]}, size:4, at: serverTimestamp()}); return b.commit(); })()));
await t('history: members read', ok(getDocs(collection(M,'history'))));
await t('ended: marks locked', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
await t('ended: text readable', ok(getDoc(doc(K,'texts',itA.id))));
await t('ended: still not about self', no(getDoc(doc(K,'texts',itM.id))));
await t('ended: admin new game (clears marks)', ok((() => { const b = writeBatch(A); b.set(doc(A,'game','state'), {status:'entry', cards:{}}); b.set(doc(A,'marks','עדי'), {marked:[],bingo:false,blackout:false,bingoAt:null,blackoutAt:null}); return b.commit(); })()));
// ---- game settings: founders manage players, admins and the family code ----
const P6 = ['אבא','אמא','מתן','אורי','עדי','הדר'];
const cfg = (d, v) => setDoc(doc(d,'config','settings'), {players:[...P6,'סבתא'], admins:['עדי'], adminUids:['kidU'], ...v});
await t('settings: non-founder cannot write', no(cfg(K)));
await t('settings: founders must stay', no(cfg(A, {players:['אבא','אמא']})));
await t('settings: admins must be players', no(cfg(A, {admins:['hacker']})));
await t('settings: max 12 players', no(cfg(A, {players:[...P6, ...'abcdefg'.split('')]})));
await t('settings: extra field', no(cfg(A, {x:1})));
await t('settings: founder saves', ok(cfg(A)));
await t('settings: second founder saves', ok(cfg(U)));
await t('settings: members read', ok(getDoc(doc(M,'config','settings'))));
await t('settings: stranger cannot read', no(getDoc(doc(X,'config','settings'))));
await t('extra admin writes the game', ok(setDoc(doc(K,'game','state'), {status:'entry', cards:{}})));
await t('extra admin cannot change settings', no(cfg(K)));
const G = db('grandU');
await t('new player joins and claims', ok(setDoc(doc(G,'members','grandU'), {code:'FAMILY_CODE'}).then(()=>setDoc(doc(G,'players','סבתא'), {uid:'grandU'}))));
await t('prediction about the new player', ok(add(K, 'עדי', 'סבתא')));
await t('still no unknown names', no(setDoc(doc(G,'players','hacker'), {uid:'grandU'})));
await t('secret: non-founder cannot read', no(getDoc(doc(K,'config','secret'))));
await t('secret: code too short', no(setDoc(doc(A,'config','secret'), {code:'ab'})));
await t('secret: founder sets a new code', ok(setDoc(doc(A,'config','secret'), {code:'new-code'})));
await t('secret: founder reads it', ok(getDoc(doc(U,'config','secret'))));
const N1 = db('newU1'), N2 = db('newU2');
await t('old fallback code no longer works', no(setDoc(doc(N1,'members','newU1'), {code:'FAMILY_CODE'})));
await t('new code works', ok(setDoc(doc(N2,'members','newU2'), {code:'new-code'})));
await t('admin removed -> no admin rights', ok(cfg(A, {admins:[], adminUids:[]})).then(() => t('…cannot write the game', no(setDoc(doc(K,'game','state'), {status:'entry', cards:{}})))));
// "new trip" cleanup: one admin batch deleting many items, texts and ratings (stays under the rules' get() limits)
const many = []; for (let i = 0; i < 40; i++) many.push((await add(K, 'עדי', 'אבא', {text:'t'+i})).id);
await t('new trip: admin bulk delete in one batch', ok((() => { const b = writeBatch(A); many.forEach(id => { b.delete(doc(A,'items',id)); b.delete(doc(A,'texts',id)); }); return b.commit(); })()));
await t('history: non-admin cannot delete', no(getDocs(collection(M,'history')).then(s => deleteDoc(doc(M,'history',s.docs[0].id)))));
await t('history: admin deletes', ok(getDocs(collection(A,'history')).then(s => deleteDoc(doc(A,'history',s.docs[0].id)))));
await t('other collection', no(setDoc(doc(A,'junk','x'), {a:1})));
console.log(`${n} passed, ${bad} failed`);
await env.cleanup(); process.exit(bad ? 1 : 0);
