// Firestore rules tests against ../../firestore.rules on the local emulator (needs Java).
// Run from tests/: `npm run test:rules`. The family code in the rules file is the placeholder
// FAMILY_CODE, so the tests join with that. Each t() line is one allow/deny case.
import { initializeTestEnvironment, assertSucceeds as ok, assertFails as no } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { Timestamp, doc, setDoc, getDoc, getDocs, addDoc, deleteDoc, collection, serverTimestamp, writeBatch } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'demo-bingo', firestore: { rules: readFileSync(new URL('../../firestore.rules', import.meta.url),'utf8'), host:'127.0.0.1', port:8080 } });
const db = u => u ? env.authenticatedContext(u).firestore() : env.unauthenticatedContext().firestore();
const A = db('adminU'), K = db('kidU'), X = db('strangerU'), anon = db(null);
let n=0, bad=0; const t = async (name, p) => { try { await p; n++; } catch(e) { bad++; console.log('FAIL', name, e.message.split('\n')[0]); } };
const add = (d, author, about='אבא', {text='עוד 5 דקות', id, ...meta}={}) => {
  const r = id ? doc(d,'items',id) : doc(collection(d,'items')); const b = writeBatch(d);
  b.set(r, {about, author, weight:1, at: serverTimestamp(), ...meta}); b.set(doc(d,'texts',r.id), {text});
  return b.commit().then(() => r);
};
const del = (d, id) => { const b = writeBatch(d); b.delete(doc(d,'items',id)); b.delete(doc(d,'texts',id)); return b.commit(); };

await t('anon read items', no(getDocs(collection(anon,'items'))));
await t('stranger read items', no(getDocs(collection(X,'items'))));
await t('wrong code', no(setDoc(doc(X,'members','strangerU'), {code:'nope'})));
await t('join for other uid', no(setDoc(doc(X,'members','kidU'), {code:'FAMILY_CODE'})));
await t('stranger claim', no(setDoc(doc(X,'players','עדי'), {uid:'strangerU'})));
await t('admin join', ok(setDoc(doc(A,'members','adminU'), {code:'FAMILY_CODE'})));
await t('kid join', ok(setDoc(doc(K,'members','kidU'), {code:'FAMILY_CODE'})));
await t('get own member', ok(getDoc(doc(K,'members','kidU'))));
await t('get other member', no(getDoc(doc(K,'members','adminU'))));
await t('admin claim', ok(setDoc(doc(A,'players','מתן'), {uid:'adminU'})));
await t('kid claim taken', no(setDoc(doc(K,'players','מתן'), {uid:'kidU'})));
await t('kid claim for other uid', no(setDoc(doc(K,'players','עדי'), {uid:'adminU'})));
await t('kid claim bad name', no(setDoc(doc(K,'players','hacker'), {uid:'kidU'})));
await t('kid claim', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'})));
await t('member read items', ok(getDocs(collection(K,'items'))));
await t('item ok', ok(add(K, 'עדי')));
await t('item impersonate', no(add(K, 'אמא')));
await t('item about self', no(add(K, 'עדי','עדי')));
await t('item too long', no(add(K, 'עדי','אבא',{text:'x'.repeat(141)})));
await t('item extra field', no(add(K, 'עדי','אבא',{evil:1})));
await t('item weight', no(add(K, 'עדי','אבא',{weight:99})));
await t('item custom id xss', no(add(K, 'עדי', 'אבא', {id:'"><img src=x onerror=alert(1)>'})));
const kidItem = await add(K, 'עדי');
const admItem = await add(A, 'מתן','עדי');
await t('kid delete admin item', no(del(K, admItem.id)));
await t('item without text', no(addDoc(collection(K,'items'), {about:'אבא', author:'עדי', weight:1, at: serverTimestamp()})));
await t('text without item', no(setDoc(doc(K,'texts','abcdefghijklmnopqrst'), {text:'x'})));
await t('item with text field', no(add(K, 'עדי', 'אבא', {extraText:'x'})));
await t('entry: author reads own text', ok(getDoc(doc(K,'texts',kidItem.id))));
await t('entry: admin cannot read kid text', no(getDoc(doc(A,'texts',kidItem.id))));
await t('entry: kid cannot read admin text', no(getDoc(doc(K,'texts',admItem.id))));
await t('entry: kid cannot list texts', no(getDocs(collection(K,'texts'))));
await t('stranger cannot read text', no(getDoc(doc(X,'texts',kidItem.id))));
await t('kid update item', no(setDoc(doc(K,'items',kidItem.id), {about:'אמא', author:'עדי', weight:1, at: serverTimestamp()})));
await t('kid write game', no(setDoc(doc(K,'game','state'), {status:'entry', cards:{}})));
await t('kid write other marks', no(setDoc(doc(K,'marks','מתן'), {marked:[],bingo:true,blackout:true})));
await t('kid write own marks in entry', no(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:false,blackout:false})));
await t('marks junk', no(setDoc(doc(K,'marks','עדי'), {marked:'x',bingo:false,blackout:false})));
const b = writeBatch(A);
b.set(doc(A,'game','state'), {status:'play', cards:{'עדי':['a']}, at: serverTimestamp()});
['אבא','אמא','מתן','עדי','עדי','הדר'].forEach(p => b.set(doc(A,'marks',p), {marked:[],bingo:false,blackout:false}));
await t('admin generate batch', ok(b.commit()));
await t('play: kid write own marks', ok(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:true,blackout:false,bingoAt:serverTimestamp(),blackoutAt:null})));
await t('play: keep same bingoAt', ok(getDoc(doc(K,'marks','עדי')).then(s=>setDoc(doc(K,'marks','עדי'), {...s.data(), marked:['a','b']}))));
await t('play: forged bingoAt', no(setDoc(doc(K,'marks','עדי'), {marked:['a'],bingo:true,blackout:false,bingoAt:Timestamp.fromDate(new Date(2000,1,1)),blackoutAt:null})));
await t('play: marks too many', no(setDoc(doc(K,'marks','עדי'), {marked:Array(26).fill('x'),bingo:false,blackout:false})));
await t('play: admin reads kid text (about אבא)', ok(getDoc(doc(A,'texts',kidItem.id))));
await t('play: kid cannot read text about himself', no(getDoc(doc(K,'texts',admItem.id))));
await t('item during play', no(add(K, 'עדי')));
await t('own delete during play', no(del(K, kidItem.id)));
await t('admin reset', ok(setDoc(doc(A,'game','state'), {status:'entry', cards:{}})));
await t('own delete in entry', ok(del(K, kidItem.id)));
await t('admin delete kid item', ok(del(A, admItem.id)));
await t('kid release admin', no(deleteDoc(doc(K,'players','מתן'))));
await t('admin release kid', ok(deleteDoc(doc(A,'players','עדי'))));
await t('kid reclaim', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'})));
await t('kid release self', ok(deleteDoc(doc(K,'players','עדי'))));
await t('kid set own look', ok(setDoc(doc(K,'players','עדי'), {uid:'kidU'}).then(()=>setDoc(doc(K,'looks','עדי'), {e:'🚀'}))));
await t('kid look not in list', no(setDoc(doc(K,'looks','עדי'), {e:'💩'})));
await t('kid look extra field', no(setDoc(doc(K,'looks','עדי'), {e:'🚀', x:1})));
await t('kid set other look', no(setDoc(doc(K,'looks','אמא'), {e:'🚀'})));
await t('stranger read looks', no(getDocs(collection(X,'looks'))));
const U = db('uriU');
await t('uri join+claim', ok(setDoc(doc(U,'members','uriU'), {code:'FAMILY_CODE'}).then(()=>setDoc(doc(U,'players','אורי'), {uid:'uriU'}))));
await t('uri admin: write game', ok(setDoc(doc(U,'game','state'), {status:'entry', cards:{}})));
await t('uri admin: set other look', ok(setDoc(doc(U,'looks','אמא'), {e:'👻'})));
await t('uri admin: release kid', ok(deleteDoc(doc(U,'players','עדי'))));
await t('kid (released) write own marks', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
// ---- rating phase, sizes, history ----
const M = db('momU');
await setDoc(doc(K,'players','עדי'), {uid:'kidU'});
await setDoc(doc(M,'members','momU'), {code:'FAMILY_CODE'}); await setDoc(doc(M,'players','אמא'), {uid:'momU'});
const itA = await add(A,'מתן','אמא'), itK = await add(K,'עדי','אבא'), itM = await add(M,'אמא','עדי');
const rt = (d, item, player, stars, id) => setDoc(doc(d,'ratings', id ?? `${item}_${player}`), {item, player, stars});
await t('entry: kid cannot rate', no(rt(K, itA.id, 'עדי', 3)));
await t('kid cannot start rating', no(setDoc(doc(K,'game','state'), {status:'rate', cards:{}, raters:['עדי'], raterUids:['kidU']})));
await t('admin: bad rater name', no(setDoc(doc(A,'game','state'), {status:'rate', cards:{}, raters:['hacker']})));
await t('admin starts rating', ok(setDoc(doc(A,'game','state'), {status:'rate', cards:{}, raters:['עדי','מתן'], raterUids:['kidU','adminU'], at: serverTimestamp()})));
await t('admin syncs raterUids (merge)', ok(setDoc(doc(A,'game','state'), {raterUids:['kidU','adminU']}, {merge:true})));
await t('kid cannot sync raterUids', no(setDoc(doc(K,'game','state'), {raterUids:['kidU']}, {merge:true})));
await t('rate: rater reads text', ok(getDoc(doc(K,'texts',itA.id))));
await t('rate: non-rater cannot read text', no(getDoc(doc(M,'texts',itK.id))));
await t('rate: rater cannot read text about self', no(getDoc(doc(K,'texts',itM.id))));
await t('rate: author still reads own', ok(getDoc(doc(M,'texts',itM.id))));
await t('rate: kid rates', ok(rt(K, itA.id, 'עדי', 3)));
await t('rate: kid changes rating', ok(rt(K, itA.id, 'עדי', 0)));
await t('rate: about self', no(rt(K, itM.id, 'עדי', 3)));
await t('rate: own prediction', no(rt(K, itK.id, 'עדי', 3)));
await t('rate: 4 stars', no(rt(K, itA.id, 'עדי', 4)));
await t('rate: as someone else', no(rt(K, itA.id, 'מתן', 3)));
await t('rate: id mismatch', no(rt(K, itA.id, 'עדי', 3, 'whatever')));
await t('rate: non-rater', no(rt(M, itK.id, 'אמא', 3)));
await t('rate: extra field', no(setDoc(doc(K,'ratings',`${itA.id}_עדי`), {item:itA.id, player:'עדי', stars:1, x:1})));
await t('rate: add item locked', no(add(K, 'עדי')));
await t('rate: delete item locked', no(del(K, itK.id)));
await t('rate: marks locked', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
await t('members read ratings', ok(getDocs(collection(M,'ratings'))));
await t('admin: size 6', no(setDoc(doc(A,'game','state'), {status:'play', cards:{}, size:6})));
await t('admin: bad status', no(setDoc(doc(A,'game','state'), {status:'weird', cards:{}})));
await t('admin: play 4x4', ok(setDoc(doc(A,'game','state'), {status:'play', cards:{'עדי':[itA.id]}, size:4, at: serverTimestamp()})));
await t('play: rating locked', no(rt(K, itA.id, 'עדי', 2)));
await t('history: kid cannot write', no(addDoc(collection(K,'history'), {at: serverTimestamp(), size:4, results:[]})));
await t('history: extra field', no(addDoc(collection(A,'history'), {at: serverTimestamp(), size:4, results:[], x:1})));
await t('history: admin saves + ends', ok((() => { const b = writeBatch(A); b.set(doc(collection(A,'history')), {at: serverTimestamp(), size:4, results:[{p:'עדי', place:1, n:3, bingo:true, blackout:false}]}); b.set(doc(A,'game','state'), {status:'ended', cards:{'עדי':[itA.id]}, size:4, at: serverTimestamp()}); return b.commit(); })()));
await t('history: members read', ok(getDocs(collection(M,'history'))));
await t('ended: marks locked', no(setDoc(doc(K,'marks','עדי'), {marked:[],bingo:false,blackout:false})));
await t('ended: text readable', ok(getDoc(doc(K,'texts',itA.id))));
await t('ended: still not about self', no(getDoc(doc(K,'texts',itM.id))));
await t('ended: admin new game (clears marks)', ok((() => { const b = writeBatch(A); b.set(doc(A,'game','state'), {status:'entry', cards:{}}); b.set(doc(A,'marks','עדי'), {marked:[],bingo:false,blackout:false,bingoAt:null,blackoutAt:null}); return b.commit(); })()));
await t('other collection', no(setDoc(doc(A,'junk','x'), {a:1})));
console.log(`${n} passed, ${bad} failed`);
await env.cleanup(); process.exit(bad ? 1 : 0);
